SET DEFINE OFF

DECLARE
  objExists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO objExists FROM ALL_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OWNER = 'FEY' AND OBJECT_NAME = 'DUMMY_DATA';
  IF (objExists > 0) THEN
    EXECUTE IMMEDIATE 'DROP TABLE fey.dummy_data';
  END IF;
END;
/

