SET DEFINE OFF

DECLARE
  objExists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO objExists FROM ALL_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OWNER = 'FEY' AND OBJECT_NAME = 'APP_ROLE';
  IF (objExists > 0) THEN
    EXECUTE IMMEDIATE 'DROP TABLE fey.app_role';
  END IF;
END;
/

DECLARE
  objExists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO objExists FROM ALL_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OWNER = 'FEY' AND OBJECT_NAME = 'CATEGORY';
  IF (objExists > 0) THEN
    EXECUTE IMMEDIATE 'DROP TABLE fey."CATEGORY"';
  END IF;
END;
/

