SET DEFINE OFF

CREATE TABLE fey.app_role (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  role_name VARCHAR2(50 BYTE) NOT NULL,
  PRIMARY KEY (role_id),
  UNIQUE (role_name)
);

CREATE TABLE fey."CATEGORY" (
  category_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  category_name VARCHAR2(50 BYTE) NOT NULL,
  PRIMARY KEY (category_id),
  UNIQUE (category_name)
);

